### ISSUE TITLE
Input audio not working on Mac standalone build

### ISSUE THREAD

**Issue by ylevtov** [LIMUNIMI/Real-time-SDN#1]
Running the Mac standalone build doesn't seem to process input audio:
<img width="523" alt="image" src="https://github.com/LIMUNIMI/Real-time-SDN/assets/294772/a8a4ebe1-793c-4d9a-a7ea-dcd9f58c34ac">

The VU-meter bars don't seem to be moving. 

Have tried with the In-built Microphone, as well as Blackhole (internal audio-routing application for Mac).

**Comment by MarcoFontana** [comment]
Thank you for the report, I think we forgot to request microphone access for Mac.

I don't have a Mac to test it on right now, so if you could, please let me know if the latest push fixed it.

**Comment by ylevtov** [comment]
Great - that fixed it 👍
